name: SRMA - Auto Screen (Title/Abstract)

on:
  workflow_dispatch:        # 手动触发
  push:                     # 以下文件变化时自动触发
    paths:
      - 'code/07_autoscreen.py'
      - 'data_clean/TitleAbs_Screening.xlsx'
      - 'data_clean/master_refs_raw.csv'

jobs:
  autoscreen:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # 允许把生成的 Excel 回写到仓库
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Run autoscreen
        run: python code/07_autoscreen.py

      - name: Commit AUTO workbook
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data_clean/TitleAbs_Screening_AUTO.xlsx
          git commit -m "autoscreen: add/update TitleAbs_Screening_AUTO.xlsx" || echo "Nothing to commit"
          git push
