name: SRMA - Make Title/Abstract Screening Sheet
on:
  workflow_dispatch:
  push:
    paths:
      - 'data_clean/master_refs_dedup.csv'
      - 'data_clean/master_refs_raw.csv'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show tree
        run: |
          ls -la
          echo "---- code ----"; ls -la code || true
          echo "---- data_clean ----"; ls -la data_clean || true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Preflight checks
        run: |
          test -f code/06_make_screening_sheet.py || (echo "MISSING: code/06_make_screening_sheet.py" && exit 1)
          (test -f data_clean/master_refs_dedup.csv || test -f data_clean/master_refs_raw.csv) || (echo "MISSING: master_refs_dedup.csv or master_refs_raw.csv" && exit 1)

      - name: Generate screening sheet
        run: python code/06_make_screening_sheet.py

      - name: Commit screening sheet
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data_clean/TitleAbs_Screening.xlsx
          git commit -m "add/update TitleAbs_Screening.xlsx (auto)" || echo "Nothing to commit"
          git push
