name: SRMA - Ingest & Deduplicate Citations

on:
  push:
    paths:
      - 'data_raw/**'
      - 'code/merge_bibliography.py'
      - 'requirements.txt'
      - '.github/workflows/merge_bib.yml'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Merge & deduplicate
        run: |
          python code/merge_bibliography.py --raw data_raw --out data_clean

      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data_clean/*
          git commit -m "chore: update merged bibliography (auto)" || echo "no changes"
          git push
